name: Deploy Project

on:
  push:
    branches:
      - master
jobs:
  update-project:
    runs-on: ubuntu-latest
    
    steps:
    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.REMOTE_USER }}/${{ github.event.repository.name }}
          git pull
          source .venv/bin/activate
          poetry install